barn/barn/urls.py
from django.conf.urls import url
from django.contrib import admin
from app import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.barn_view, name="barn")
]

barn/app/models.py
from django.db import models

# Create your models here.
class Animal(models.Model):
	GENDER_MALE = 'M'
	GENDER_FEMALE = 'F'
	GENDER_OTHER = 'O'
	GENDER_CHOICES = (
		(GENDER_MALE, 'Mann'),
		(GENDER_FEMALE, 'Kvinne'),
		(GENDER_OTHER, 'Annet')
	)
	gender = models.CharField(
		max_length=1,
		choices=GENDER_CHOICES,
		default=GENDER_OTHER
	)
	SPECIES_COW = 0
	SPECIES_CHCIKEN = 1
	SPECIES_PIG = 2
	SPECIES_SHEEP = 3
	SPECIES_HORSE = 4
	SPECIES_RABBIT = 5
	SPECIES_DONKEY = 6
	SPECIES_POLARBEAR = 7
	SPECIES_WOLF = 8
	SPECIES_PARROT = 9
	SPECIES_OCELOT = 10
	SPECIES_LLAMA = 11
	SPECIES_MULE = 12
	SPECIES_BAT = 13
	SPECIES_SQUID = 14
	SPECIES_CHOICES = (
		(SPECIES_COW, 'Ku'),
		(SPECIES_CHCIKEN, 'Kylling'),
		(SPECIES_PIG, 'Gris'),
		(SPECIES_SHEEP, 'Sau'),
		(SPECIES_HORSE, 'Hest'),
		(SPECIES_RABBIT, 'Kanin'),
		(SPECIES_DONKEY, 'Esel'),
		(SPECIES_POLARBEAR, 'Isbjørn'),
		(SPECIES_WOLF, 'Ulv'),
		(SPECIES_PARROT, 'Papegøye'),
		(SPECIES_OCELOT, 'Ozelot'),
		(SPECIES_LLAMA, 'Llama'),
		(SPECIES_MULE, 'Muldyr'),
		(SPECIES_BAT, 'Flaggermus'),
		(SPECIES_SQUID, 'Blekksprut')
	)
	species = models.IntegerField(choices=SPECIES_CHOICES)
	name = models.CharField(max_length=255)
	age = models.PositiveIntegerField()
	description = models.TextField(null=True, blank=True)
	# TODO delete everything

barn/app/forms.py
from django import forms
from .models import Animal

class AnimalForm(forms.ModelForm):
	class Meta:
		model = Animal
		fields = ['name', 'species', 'age', 'gender', 'description']
		labels = {
			'name' : 'Navn',
			'species' : 'Art',
			'age' : 'Alder',
			'gender' : 'Kjønn',
			'description' : 'Beskrivelse'
		}

barn/app/views.py
from django.shortcuts import render
from .models import *
from .forms import AnimalForm

# Create your views here.
def barn_view(request):
	ark = Animal.objects.all()
	if request.method == 'POST':
		if 'delete' in request.POST:
			Animal.objects.get(id =request.POST['delete']).delete()
			
		form = AnimalForm(request.POST)
		if form.is_valid():
			animal = form.save()
	form = AnimalForm()

	return render(request, 'barn.html', {
			'ark' : ark,
			'form' : form
		})

barn/app/templates/barn.html
<head>
  	{% load staticfiles %}
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
	<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
  	<script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>
	<div class="row">
		<div class="col-lg-12" style="margin-left: 25px">
			<h1>TP-fjøset</h1>
			<div class="container">
				<div class="panel-group" id="accordion">
					{% for animal in ark %}
						<div class="panel panel-default">
							<div class="panel-heading" style="background: rgb(10, 36, 54); color: white">
								<h4 class="panel-title">
									<a data-toggle="collapse" data-parent="#ac2ordion" href="#{{animal.id}}">
										{{ animal.name }}
									</a>
								</h4>
							</div>
							<div id="{{animal.id}}" class="panel-collapse collapse">
								<div class="panel-body">
									<strong>Navn:</strong>
									{{ animal.name }}
									<br>
									<strong>Art:</strong>
									{{ animal.get_species_display }}
									<br>
									<strong>Alder:</strong>
									{{ animal.age }}
									<br>
									<strong>Kjønn:</strong>
									{{ animal.get_gender_display}}
									<br>
									<strong>Beskrivelse:</strong>
									{{ animal.description }}
									<br>
									<form method="post">
										{% csrf_token %}
										<button type="submit" name="delete" value="{{ animal.id }}" style="background: rgb(154, 25, 21); color: white">Slett</button>
									</form>
								</div>
							</div>
						</div>
					{% endfor %}
				</div>
			</div>
			<form method="post">
				{% csrf_token %}
				<table class="fill">
					{{ form }}
				</table>
				<input class="g-button" type="submit" value ="Lagre">
			</form>
		</div>
	</div>
</body>